# Generated by Django 3.0.9 on 2020-08-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200804_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='role',
            field=models.CharField(default='User', max_length=7),
        ),
    ]
