# Generated by Django 3.0.9 on 2020-08-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='mobileno',
            field=models.CharField(default=423432423, max_length=12),
            preserve_default=False,
        ),
    ]
